### PR TITLE
 dcache: Removed FTPTransactionLog class

### PR DESCRIPTION
**Pull request by HWittlich**
Motivation:
Historical FTPTransactionLog class not needed anymore.

Modification:
Removed class and its uses in AbstractFtpDoorV1.java and TransferManagerhandler.java.

Result:
FTP TransactionLog class removed.

Fixes: #3811
Ticket: #rt-number
Acked-by:
Target: master
Require-book: yes
Require-notes: yes

### CODE REVIEW

**Comment by kofemann** [comment]
ok to test

**Comment by jstarek** [comment]
retest this please

**Comment by kofemann** [comment]
retest this please

**Comment by kofemann** [comment]
ok to test

**Comment by kofemann** [comment]
Thanks!

**Pull request merged**
