### PR TITLE
skel: remove legacy Berkeley DB jar and corresponding preupgrade-script

### PR DESCRIPTION
**Pull request by sischulte**
Motivation:
The script and the legacy JE jar file can be removed in dCache 2.7.

Modification:
Deleted skel/share/misc/je-4.1.21.jar and skel/sbin/dcache-pool-meta-preupgrade

Result:
Script and legacy jar removed.

Signed-off-by: Sarah <s0551906@htw-berlin.de>

### CODE REVIEW

**Comment by kofemann** [comment]
Thanks for the pool request!

**Comment by kofemann** [comment]
You will need to update modules/dcache/src/main/java/org/dcache/pool/repository/meta/db/BerkeleyDBMetaDataRepository.java to remove reference to the script

**Comment by sischulte** [comment]
The reference to the script in BerkeleyDBMetaDataRepository.java has already been removed in commit 923fbe5.

**Comment by kofemann** [comment]
Oh, my bad! Thanks!

**Pull request merged**
