### PR TITLE
Add Kafka producer to transfer manager.

### PR DESCRIPTION
**Pull request by paurkedal**
This is a proposed solution to #6298.

### CODE REVIEW

**Comment by mksahakyan** [comment]
retest this please

**Comment by kofemann** [comment]
retest this please

**Comment by kofemann** [comment]
Thanks!

**Comment by paurkedal** [comment]
And thanks for reviewing!  With this and #7546, we're close to having the full billing logs for our usage in Kafka according to empirical comparison.  (The remaining missing records are from NFS, which I couldn't quite locate where to implement, but it's only internal traffic for us, anyway.)

**Comment by paurkedal** [comment]
After reproducing the billing entries in our test setup, I can confirm that "request" records from NFS cells are now present also in Kafka.  My original comparison was done on our production setup, where we are running dCache 9.2.11.  I have a suspicion that "remove" records like the following are missing, still, but it could be my dCache build is too old:
```
05.02 15:45:23 [door:NFS-headnode1-x@nfs-headnode1-xDomain:remove] ["":0:0:127.0.0.1] [000042EB85512F314B498516FF443E5396CC,0] [parent:[0000A1260353F71D44819567ED4C6AD028F2]/test.txt] <Unknown> 0 0 {0:""}
```

**Comment by paurkedal** [comment]
I retried the test from my previous comment with a build from today's master branch, and I can confirm that "remove" records from NFS doors are missing.

**Pull request merged**
