### PR TITLE
dcache: Removed uses of ExtendedRunnable Interface and replace with r…

### PR DESCRIPTION
**Pull request by HWittlich**
…egular Runnable

Motivation:
The ExtendedRunnable provides  the runFailed method to be called on errors.
However, after a series of refactorings runFailed is not used anymore.
As a result, ExtendedRunnable can be replaced by a regular Runnable.

Modification:
Removed ExtendedRunnable Interface and replaced use with with regular Runnable.
Deleted runFailed in RequestContainerV5.java.

Result:
ExtendedRunnable no longer used.

Fixes: #3809
Ticket: #rt-number
Acked-by:
Target: master
Require-book: yes
Require-notes: yes

### CODE REVIEW

**Comment by jstarek** [comment]
ok to test

**Comment by kofemann** [comment]
retest this please

**Comment by kofemann** [comment]
ok to test

**Comment by kofemann** [comment]
pleas update commit message to make it shorter (60 chars):

dcache: removed  ExtendedRunnable in favour of Runnable

Please commit with '-s' option

**Comment by kofemann** [comment]
retest this please

**Comment by kofemann** [comment]
contributor didn't update the patch. Closing.

**Pull request closed without merging**
