### PR TITLE
fix modul acl, chimera and dcache [dcache-core]

### PR DESCRIPTION
**Pull request by MichaelSchwabe**
#3807 fix modul acl with static LOGGER from (_log,logger,LOG .... )

### CODE REVIEW

**Comment by MichaelSchwabe** [comment]
#3807 fix modul chimera with static LOGGER from (_log,logger,LOG .... ) in all classes (include testclasses)

**Comment by MichaelSchwabe** [comment]
#3807 fix modul chimera with static LOGGER from (_log,logger,LOG .... ) in all classes (include testclasses) ..... i delete one line of declaration in the code. The Logger instance never used in this class.

**Comment by einhorntee** [comment]
It looks like you didn't checkout a new branch after commiting the change of the readme. Also, `FIX MY MISTAKE` is not the best commit message one could chose.
You can fix both by using `git rebase -i HEAD~10` and then 
* write `d` instead of `pick` in front of the `chimera: create readme.md`-commit.
* write `s` in front of all commits with less meaningful commit messages to squash them into the commit above them. You can also change the order of the commits in order to make sure the fixes are in line with the changes in `common-security` and `dcache-core` respectively.

Then: `git push --force`

**Comment by jobegrabber** [comment]
> Then: `git push --force`

Quick note: Better to use `git push --force-with-lease` instead. This will throw an error if the state of the remote branch changed since the last invocation of `git fetch` and similar commands. Thus `--force-with-lease` will prevent you from overriding changes pushed to the remote branches that have not been fetched/pulled to one's local repository.

There's rarely a necessity to use `git push --force` over `git push --force-with-lease`.

**Comment by kofemann** [comment]
ok to test

**Comment by kofemann** [comment]
@jobegrabber our build system still unhappy.

**Comment by kofemann** [comment]
@MichaelSchwabe our build system still unhappy.

**Comment by MichaelSchwabe** [comment]
So far I have fixed everything that went wrong with the build. Please check the code

**Comment by jstarek** [comment]
Closing this PR, that seems to have been just a test, due to long inactivity. Feel free to re-submit once the outstanding issues are resolved.

**Pull request closed without merging**
