### PR TITLE
Comment frontend.dcache-view.org-name: no quotation marks

### PR DESCRIPTION
**Pull request by onnozweers**

### CODE REVIEW

**Comment by paulmillar** [comment]
ok to test

**Comment by femiadeyemi** [comment]
Thanks @onnozweers! 
@paulmillar I think this should fix https://github.com/dCache/dcache/issues/3231
If @paulmillar agree, @jstarek may you please merge and backport up to 2.16, thanks.

**Comment by paulmillar** [comment]
@femiadeyemi this patch should be back-ported to all branches back to (and including) 2.16, since it accurately describes the current situation: the value cannot contain quote marks.

#3231 is a bug, something that simply adding documentation doesn't fix 😉 Instead, to fix this bug, dCache needs to be updated so that including double-quotes in the value is perfectly fine.

Ideally, what should have happened is that the admin included the double-quotes, sees a working dCache-View that has a organisation name that also has these double-quotes and realises that this isn't what is wanted, so removes them.

**Comment by paulmillar** [comment]
Hi @onnozweers,

Thanks again for making this pull-request.

As it happens, the problem was relatively easy to fix.  The limitation is gone with dCache releases v2.16.40, v3.0.21 and v3.1.9.  With these versions of dCache, quote-marks are perfectly acceptable in the org name.

Therefore, I'm closing this pull-request.

**Pull request closed without merging**
