### PR TITLE
Add Kafka producer to SRM manager.

### PR DESCRIPTION
**Pull request by paurkedal**
Sends messages for putDone, abortPut, and removeFile corresponding to what's written to billing logs.

This is a proposed solution to #5314.

### CODE REVIEW

**Comment by mksahakyan** [comment]
retest this please

**Comment by kofemann** [comment]
@paurkedal Thanks for the changes. Before we merge, could you please sign your commit `Signed-off-by:` as described in [How to contribute](https://github.com/dCache/dcache?tab=readme-ov-file#how-to-contribute) section

**Comment by paurkedal** [comment]
It's hereby signed off and rebased to master.

**Comment by kofemann** [comment]
retest this please

**Comment by kofemann** [comment]
Thanks, @paurkedal!

**Comment by kofemann** [comment]
@paurkedal looks like your pull-request broke simple taste cas, where kafka is not enabled
```
10 May 2024 18:29:41 (System) [] Bug detected in dCache; please report this to <support@dcache.org> with the following information.
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.kafka.core.KafkaTemplate<?, ?>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1801)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1357)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.resolveMethodArguments(AutowiredAnnotationBeanPostProcessor.java:760)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:720)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.dcache.cells.UniversalSpringCell.createContext(UniversalSpringCell.java:1067)
	at org.dcache.cells.UniversalSpringCell.starting(UniversalSpringCell.java:235)
	at dmg.cells.nucleus.CellAdapter.prepareStartup(CellAdapter.java:689)
	at dmg.cells.nucleus.CellNucleus.doStart(CellNucleus.java:899)
	at dmg.cells.nucleus.CellNucleus.lambda$wrapLoggingContext$2(CellNucleus.java:725)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:247)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at dmg.cells.nucleus.CellNucleus.lambda$wrapLoggingContext$2(CellNucleus.java:725)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

**Pull request merged**
