### PR TITLE
FTPServerFacade: refactoring slf4j logging messages

### PR DESCRIPTION
**Pull request by lalottacontinua**
Motivation: with normal string concatenations in log-messages strings are always build, regardless if log-level is activated or not. with parameterized log-messages the strings only become build, when the log-level is activated;

Modification: using placeholder with parameterized messages instead of string concatenations

Result: gained efficiency

Signed-off-by: Lotta Rüger <s0551814@htw-berlin.de>

### CODE REVIEW

**Comment by lalottacontinua** [comment]
Would I do a new pull request for that (changing the language of "Modul" to english) or do I just make a new commit? And is the pull request already merged with the master?

**Comment by alrossi** [comment]
You can just modify and commit.  The pull request should be automatically updated.  It hasn't been merged yet.

**Comment by alrossi** [comment]
Lotta, did you modify the same branch used to make the original pull request?  It seems this commit created a conflict.

**Comment by lalottacontinua** [comment]
sry. I'm a little confused. I thought, I had already committed the readme.md in an earlier pull-request. and I thought, I had been doing the change on the same branch, but maybe I did the checkout after I edited the file. I'll try to further fix this...

**Comment by alrossi** [comment]
The rebase fixed it.  Thanks!

**Comment by lalottacontinua** [comment]
Thank you! 
I'm going to do more of this kind of refactoring. I'll use different branches for this, as it'll be in different classes/modules. Is that correct/ should I do so? And do you think I should test the refactoring somehow or are the automatically tests after merge sufficient in this case?

**Comment by alrossi** [comment]
OK, I see what happened here, I think.   We need to return to base one.

Could you possibly do the following:

1.  update your current branch of master first, to make sure that your ReadMe commit is there.
2. make a new pull request with all the slf4j changes you intend to do.  If that is all the patch does, it can embrace different classes.  You don't need a different request for each one.  But make sure you don't do anything else except change the log statements in the patch (the purpose of the patch).
3. when you are done, create a new pull request.

We will close this one (i.e., discard it).

Thanks, Al

**Comment by alrossi** [comment]
P.S. Don't worry about the German in the ReadMe.

**Pull request closed without merging**
