### PR TITLE
pinmanager unpinprocessor: add debugging info

### PR DESCRIPTION
**Pull request by onnozweers**
Here are some suggestions for debugging info to have a better idea what the pinmanager is doing and whether it is processing pins in "unpinning" state. This helped me to better understand issue #4825. Feel free to adjust messages and log levels (perhaps some things should be trace level instead of debug).

### CODE REVIEW

**Comment by paulmillar** [comment]
ok to test

**Comment by paulmillar** [comment]
I like the idea of this patch, but I think it could be done "better".  For example, the pin deletion messages (I think) belong within the DAO and I would add some of the logged information in the context, rather than explicitly in the message.

**Comment by onnozweers** [comment]
Hi Paul, I agree, but it's a bit difficult for me because the DAO does not have a logger yet, and it's not a class but an interface, and I think I've reached the edge of my very limited Java skills.

**Comment by paulmillar** [comment]
Sure, that's not a problem -- I can add something there.

**Comment by paulmillar** [comment]
Patch: https://rb.dcache.org/r/11770/

Turns out there's quite a few bugs in how logging is handled in PinManager, but I think I've got them all, now.

With this patch, you no longer need the debug statements: `_logger.debug("Deleting pin` ...

**Comment by paulmillar** [comment]
@onnozweers, could you rebase your patch against the current tip of master and retest?

I think you'll find the last two debug lines (`_logger.debug("Deleting pin`...) are not needed any more.

**Comment by jstarek** [comment]
ping @onnozweers  ;-)

**Comment by onnozweers** [comment]
I have full confidence that logging now has improved significantly. Wouldn't it just be better if I withdrew this pull request?

**Comment by onnozweers** [comment]
I've looked into rebasing but it looks complicated to me.
Can I close this pull request and submit a new one, based on the current master? That I can do.

**Comment by paulmillar** [comment]
Hi Onno,

Of course!  feel free to close this pull request and create a fresh one.

**Comment by onnozweers** [comment]
Continued in #4948.

**Pull request closed without merging**
